name: Deploy React App
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start build
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt

